Repository Hackodex-ITER/CSES-Problems, pull requests merged in 2020-10, with the labels that each got.

#2 demo case added
  java/adarsh1405/adarsh1405_weird_algorithm.java
Labels: Demo PR

#104 Added Trailing Zeros Algorithm
  java/debashishsamantara/debashishsamantara_TrailingZeros.java
Labels: hacktoberfest-accepted

#105 added repetitions
  java/Suvamrx/Suvamrx_repetition.java
Labels: hacktoberfest-accepted

#111 Added missing number solution in java
  java/RaviKumarPrasad/Raviruler_Missing_Number.java
Labels: hacktoberfest-accepted

#135 SatyapragyanDas
  java/SatyapragyanDas/SatyapragyanDas_WeirdAlgorithm.java
Labels: multiple files

#156 Added Missing Number problem.
  java/SatyapragyanDas/Satyapragyan_MissingNumber.java
Labels: multiple files

#278 added bit_strings.cpp file
  c_plus_plus/MartyMiniac/MartyMiniac_bit_strings.cpp
Labels: hacktoberfest-accepted

#255 Solved weirdAlogorithm problem
  python/ankita-04/ankita-04_bitStrings.py
  python/ankita-04/ankita-04_weirdAlgorithm.py
Labels: hacktoberfest-accepted

#284 Weird Algorithm solved
  java/Ashish Senapati/Ashish_WeirdAlgorithm.java
Labels: hacktoberfest-accepted

#280 Trailing Zeroes
  c_plus_plus/subhamsagar524/subhamsagar524_trailing_zeros.cpp
Labels: hacktoberfest-accepted

#281 BIT STRING SOLVED
  java/TapasSahu/TapasSahu_bitString.java
Labels: hacktoberfest-accepted

#286 Added two number sum solution
  python/DE-L-TA/de-l-ta_two_num_sum.py
Labels: hacktoberfest-accepted

#287 Weird Algorithm
  java/Prakashpathak984/Prakashpathak984_WeirdAlgorithm.java
Labels: hacktoberfest-accepted

#289 Missing Number
  java/Prakashpathak984/Prakashpathak984_MissingNumber.java
Labels: hacktoberfest-accepted

#288 TRAILING ZEROS SOLVED
  java/TapasSahu/TapasSahu_TrailingZeros.java
Labels: hacktoberfest-accepted

#283 Add: Solutions
  c_plus_plus/psib0t/psib0t_Appartments.cpp
  c_plus_plus/psib0t/psib0t_CoinCombinations1.cpp
  c_plus_plus/psib0t/psib0t_CoinCombinations2.cpp
  c_plus_plus/psib0t/psib0t_MovieFestival.cpp
  c_plus_plus/psib0t/psib0t_RemovingDigits.cpp
Labels: hacktoberfest-accepted

#326 added apple_division.cpp
  c_plus_plus/MartyMiniac/MartyMiniac_apple_division.cpp
Labels: hacktoberfest-accepted

#325 TwoKnight
  java/kshitizranjan15/kshitizranjan15_TwoKnight.java
Labels: hacktoberfest-accepted

#324 Increasing Array
  java/Prakashpathak984/Prakashpathak984_increasingArray.java
Labels: hacktoberfest-accepted

#290 Missing number solved
  java/Ashish Senapati/Ashish_DistinctNumbers.java
  java/Ashish Senapati/Ashish_MissingNumber.java
Labels: hacktoberfest-accepted

#340 Utkarsh's initial commit
  java/UtkarshShankar/UtkarshShankar_Weird.java
Labels: question

#418 DistinctNumbers
  python/LoopGlitch26/LoopGlitch26_DistinctNumbers.py
Labels: hacktoberfest-accepted

#419 WeirdAlgorithm
  java/LoopGlitch26/LoopGlitch26_WeirdAlgorithm.java
Labels: hacktoberfest-accepted

#420 MissingNumber
  java/LoopGlitch26/LoopGlitch26_MissingNumber.java
Labels: hacktoberfest-accepted

#424 Stuti Cses Solution
  java/JainStuti25/JainStuti25_IncreasingArr.java
  java/JainStuti25/JainStuti25_MissingNum.java
  java/JainStuti25/JainStuti25_Permutation.java
  java/JainStuti25/JainStuti25_Repetition.java
  java/JainStuti25/JainStuti25_WeirdAlgo.java
Labels: hacktoberfest-accepted

#372 Added Code for akbar1214
  c_plus_plus/akbar1214/akbar1214_BitStrings.cpp
  c_plus_plus/akbar1214/akbar1214_IncreasingArray.cpp
  c_plus_plus/akbar1214/akbar1214_MissingNumber.cpp
  c_plus_plus/akbar1214/akbar1214_TrailingZeroes.cpp
  c_plus_plus/akbar1214/akbar1214_TwoKnights.cpp
  c_plus_plus/akbar1214/akbar1214_TwoSets.cpp
  c_plus_plus/akbar1214/akbar1214_WeirdAlgorithm.cpp
  c_plus_plus/akbar1214/akbar1214_permutations.cpp
Labels: hacktoberfest-accepted, multiple files

#446 user saurabh-nikam added his contributions for hactoberfest 2020
  CONTRIBUTORS.md
  c_plus_plus/saurabhNikam/saurabh-nikam-Increasing_Array.cpp
  c_plus_plus/saurabhNikam/saurabh-nikam_Bit_String.cpp
  c_plus_plus/saurabhNikam/saurabh-nikam_Number_Spiral.cpp
  c_plus_plus/saurabhNikam/saurabh-nikam_Permitation.cpp
  c_plus_plus/saurabhNikam/saurabh-nikam_Repetitions.cpp
Labels: hacktoberfest-accepted

#436 created 6 solutions in siddhantmohanty2001 folder
  c_plus_plus/siddhantmohanty2001/siddhantmohanty2001_bitStrings.cpp
  c_plus_plus/siddhantmohanty2001/siddhantmohanty2001_coinPiles.cpp
  c_plus_plus/siddhantmohanty2001/siddhantmohanty2001_palindromeReorder.cpp
  c_plus_plus/siddhantmohanty2001/siddhantmohanty2001_trailingZeroes.cpp
  c_plus_plus/siddhantmohanty2001/siddhantmohanty2001_twoKnights.cpp
  c_plus_plus/siddhantmohanty2001/siddhantmohanty2001_twoSets.cpp
Labels: hacktoberfest-accepted

#282 Added Codes in CPP by Raman
  c_plus_plus/Raman/Graph/.cph/.Building_Roads.cpp_7e433b79cd927b9dba1a6a4298f53e3d.prob
  c_plus_plus/Raman/Graph/.cph/.Building_Teams.cpp_92e4fa58d42efc981141d3cb07c9a894.prob
  c_plus_plus/Raman/Graph/.cph/.Counting_Rooms.cpp_ae7f61321e7c7e80dfedd5c2b3aa88a2.prob
  c_plus_plus/Raman/Graph/.cph/.Labyrinth.cpp_f8635e9a69fb9d7315154109f3317af4.prob
  c_plus_plus/Raman/Graph/.cph/.Message_Route.cpp_71d5c75dbdb56d6c744588c775d202f5.prob
  c_plus_plus/Raman/Graph/.vscode/settings.json
  c_plus_plus/Raman/Graph/Raman_Building_Roads.cpp
  c_plus_plus/Raman/Graph/Raman_Building_Teams.cpp
  c_plus_plus/Raman/Graph/Raman_Counting_Rooms.cpp
  c_plus_plus/Raman/Graph/Raman_Labyrinth.cpp
  c_plus_plus/Raman/Graph/Raman_Message_Route.cpp
Labels: hacktoberfest-accepted
